/*
 * src/levels_ib1.cpp
 *
 * Static catalog of the original Icebreaker 1 levels for the
 * PACK_IB1_CLASSIC level pack.  Order matches the original 3DO release:
 * each entry's array index + 1 corresponds to the level constant of the
 * same numeric value in the original Magnet Interactive source
 * (icebreaker-master/levels.h, level constants 1..150).
 *
 * display_name is the in-grid title without surrounding quote marks; the
 * dispatcher in levels.cpp wraps it in literal quotes when formatting the
 * grid label, mirroring the original sprintf("%c%s%c",34,...,34) pattern.
 * filename is the on-disk basename in assets/Levels/, loaded via
 * $boot/IceFiles/Levels/<filename>.
 */
#include "levels_ib1.h"

const IB1LevelEntry kIB1Catalog[] = {
    { "The Rolston Level", "rolston_level" },
    { "The Eye of the Pyramid", "The_Eye_of_the_Pyramid" },
    { "Triangle Man", "Triangle_Man" },
    { "The Original Level", "original_level" },
    { "Gopher Holes", "Gopher_holes" },
    { "Yramidspay Ustmay Ieday!", "Yramidspay_Ustmay_Ieday" },
    { "Dig Your Own Grave", "dig_your_own_grave" },
    { "Pink or Swim", "pink_or_swim" },
    { "Tie Die", "Tie_Die" },
    { "One 'mid, Two 'mid", "One_mid_two_mid" },
    { "Purple Daze", "purple_daze" },
    { "The Maltese Pyramid", "The_Malteese_Pyramid" },
    { "Ice Scream", "Ice_Scream" },
    { "Gunner - Sabot - Limey", "Gunner_Sabot_Limey" },
    { "Paul is Dead", "Paul_is_Dead" },
    { "English Country Rock Garden", "english_rock_garden" },
    { "Valley of the Fourteenth Part", "Valley_of_the_Fourteenth_Part" },
    { "Pyramid-Henge", "Pyramid_Henge" },
    { "Pyramids Before Swine", "Pyramids_Before_Swine" },
    { "Double, Double, Boil and Bubble", "Double_Double_Boil_and_Bubble" },
    { "The Cracks of Doom", "The_Cracks_of_Doom" },
    { "Of Ice and Pyramids", "Of_Ice_and_Pyramids" },
    { "A Level For Chameleon", "a_level_for_chameleon" },
    { "Green Slime", "Green_Slime" },
    { "Pyramids in a Strange Land", "Pyramids_in_a_Strange_Land" },
    { "Swampwalk", "Swampwalk" },
    { "Hard Rock Zombie Pyramids", "HARD_ROCK_ZOMBIE_PYRAMIDS" },
    { "Pyramids in the Mist", "Pyramids_in_the_Mist" },
    { "Pathways in the Sand", "Pathways_in_the_sand" },
    { "The Level of Gold and Lead", "The_level_of_gold_and_lead" },
    { "Box Canyon", "box_canyon" },
    { "Crossfire", "CROSSFIRE" },
    { "Fire is Cool", "Fire_is_Cool" },
    { "Laugh While You Can", "Laugh_while_you_can" },
    { "The Fire Pit", "the_fire_pit" },
    { "Cereal Killers", "Cereal_Killers" },
    { "Don't Fall in the Moat", "dont_fall_in_the_moat" },
    { "The Fires of Heck", "The_Fires_of_Heck" },
    { "Graveyard", "Graveyard" },
    { "The Wonderful World of Alveoli", "WONDERFUL_WORLD_OF_ALVEOLI" },
    { "4 Traps for 4 Limeys", "4_traps" },
    { "Kitchen Sink", "kitchen_sink" },
    { "Right Wing Extremists", "right_wing_extremists" },
    { "No Pyramid Zone", "no_pyramid_zone" },
    { "The Blue and the Grey", "The_Blue_and_the_Grey" },
    { "Red Hot Mamma", "Red_Hot_Mamma" },
    { "All the Pyramid's Men", "all_the_pyramids_men" },
    { "12 Dudes a-Creeping", "12_dudes_a_creeping" },
    { "Random Access", "RANDOM_ACCESS" },
    { "Stoneshooter Blues", "stoneshooter_blues" },
    { "King Me", "king_me" },
    { "Icy U.", "ICY_U" },
    { "Mount St. Monday", "Mount_St._Monday" },
    { "Breakfast at Phillies", "Breakfast_at_Phillies" },
    { "The Pool of Fire", "The_pool_of_fire" },
    { "Realm of the Stonecutters", "stonecutters" },
    { "The North Pole", "the_north_pole" },
    { "The Castle of Dr. Mid", "Castle_of_Dr_Mid" },
    { "Ovens of the Molten One", "Moltars_Ovens" },
    { "They Live", "they_live" },
    { "X Marks the Spot", "x_marks_the_spot" },
    { "It's Not Easy Fleeing Green", "its_not_easy" },
    { "11 Traps for 11 Limeys", "11_traps" },
    { "Slippery Ice", "slippery_ice" },
    { "The Sea of Green", "Sea_of_Green" },
    { "Colorado", "colorado" },
    { "Fire and Ice", "fire_and_ice" },
    { "Divide and Conquer", "divide_and_conquer" },
    { "Burn Your Bridges", "burn_your_bridges" },
    { "Shattered Zones", "SHATTERED_ZONES" },
    { "Advanced Pits", "advanced_pits" },
    { "Are you the Keymaster?", "are_you_the_keymaster" },
    { "Arctic Country Rock Garden", "arctic_country_rock_garden" },
    { "New Xi City", "New_Xi_City" },
    { "Woodstock", "woodstock" },
    { "Pit of Ichor", "Pit_Of_Ichor" },
    { "Pascal's Triangles", "Pascals_triangles" },
    { "Cyanide Sandwich", "cyanide_sandwich" },
    { "Key Lime Die", "key_lime_die" },
    { "The Once and Future Pyramid", "Once_and_future_pyramid" },
    { "Bwahahahahaha", "Bwahahahahaha" },
    { "Ringworld", "ringworld" },
    { "Zombie Fountain", "zombie_fountain" },
    { "Don't Panic!", "Dont_Panic" },
    { "Pinkzilla", "pinkzilla" },
    { "Drums Over Malta", "DRUMS_OVER_MALTA" },
    { "The Hot Seat", "The_Hot_Seat" },
    { "Blue Ice", "blue_ice" },
    { "Barrier Reef", "BARRIER_REEF" },
    { "Have Fun Storming the Castle", "Have_fun_storming_the_castle" },
    { "Gateway", "GATEWAY" },
    { "In Deep", "IN_DEEP" },
    { "Spiral Death Trap", "Spiral_Death_Trap" },
    { "Slimey Pinkness", "SLIMEY_PINKNESS" },
    { "You'll Lava it", "YOU'LL_LAVA_IT" },
    { "Live and Let Slide", "Live_and_let_slide" },
    { "How the West was Won", "How_the_west_was_won" },
    { "Slime Time", "SLIME_TIME" },
    { "Dance of the Dead", "Dance_Of_The_Dead" },
    { "Moraine", "moraine" },
    { "The Oasis", "The_Oasis" },
    { "Underground Sea", "UNDERGROUND_SEA" },
    { "Tread Carefully", "TREAD_CAREFULLY" },
    { "Desert Maze", "Desert_Maze" },
    { "The Blarney Level", "blarney_level" },
    { "5 Pyramids in search of an Exit", "5_pyramids_in_search" },
    { "Hopscotch", "hopscotch" },
    { "Andy's Workshop", "Andys_workshop" },
    { "Pit Fiends", "PIT_FIENDS" },
    { "The Bad Place", "the_bad_place" },
    { "Meltdown", "MELTDOWN" },
    { "Lemmings!", "Lemmings" },
    { "Send in the Lurkers", "SEND_IN_THE_LURKERS" },
    { "The Sea of Holes", "sea_of_holes" },
    { "The Catacombs", "THE_CATACOMBS" },
    { "In the Icehouse", "In_the_icehouse" },
    { "Catwalks", "CATWALKS" },
    { "The House of Pain", "the_house_of_pain" },
    { "Iceberg", "iceberg" },
    { "Not a Nice Neighborhood", "Not_a_Nice_Neighborhood" },
    { "Bunkers", "BUNKERS" },
    { "The Valley of Death", "the_valley_of_death" },
    { "Monster Island", "monster_island" },
    { "The Cheese Shop", "the_cheese_shop" },
    { "The Fire Swamp", "The_Fire_Swamp" },
    { "Grotto", "grotto" },
    { "Radical Lefties", "radical_lefties" },
    { "Volcano", "volcano" },
    { "Bathroom Sink", "bathroom_sink" },
    { "The Curse of Pele", "Curse_of_pele" },
    { "Stop n' Go", "stop_n'_go" },
    { "Freezer of the Molten One", "Moltars_freezer" },
    { "Ninth Circle", "ninth_circle" },
    { "Lurkers Above", "lurkers_above" },
    { "Bride of the Slime Level", "bride_of_the_slime_level" },
    { "Die Die All Die", "die_die_all_die" },
    { "The Tomb", "The_Tomb" },
    { "The Quick and the Dead", "the_quick_and_the_dead" },
    { "Mantis Z's Green and Evil Level", "Zoraks_Level" },
    { "The Pyramids of Dr. Moreau", "the_pyramids_of_dr_moreau" },
    { "Lurkers on Ice", "LURKERS_ON_ICE" },
    { "The Level with No Name", "the_level_with_no_name" },
    { "Nowhere to Run", "nowhere_to_run" },
    { "Slide and Conquer", "slide_and_Conquer" },
    { "Meanyville", "meanyville" },
    { "Zombie Geyser", "zombie_geyser" },
    { "The Computer is your Friend", "the_computer_is_your_friend" },
    { "Well, You Are Dead", "WELL_YOU_ARE_DEAD" },
    { "A Green and Pleasant Level", "green_and_pleasant" },
    { "The Level that Time Forgot", "Level_That_time_forgot" },
};

const int kIB1LevelCount = (int)(sizeof(kIB1Catalog) / sizeof(kIB1Catalog[0]));
